import type { OrionRealCaseContext } from "../orion-section-pipeline/real-case-data-adapter";
import type { ReportJson } from "../types";

/** Deterministic QA fixture — no DB required for R9.7a vertical slice smoke/QA. */
export function buildQaReportSpecCaseContext(): OrionRealCaseContext {
  const now = new Date();
  const reportJson = {
    meta: { language: "ru", version: 1 },
    auditSummary: {
      headline: "Сводка аудита по России",
      summary: "Проверены открытые источники, поисковая выдача и базовые сигналы риска.",
      keyFindings: [
        "В открытых источниках присутствуют упоминания субъекта в деловом контексте.",
        "Отдельные публикации требуют ручной верификации на предмет негативного контекста.",
      ],
    },
    providerDiagnostics: {
      providers: [
        { id: "yandex", status: "ready" },
        { id: "google", status: "ready" },
      ],
    },
  } as unknown as ReportJson;

  return {
    caseId: "qa-r97a-reportspec-case",
    locale: "ru",
    subject: {
      fullName: "Иван Петров",
      aliases: ["Ivan Petrov"],
    },
    targetRegions: ["RU"],
    reportJson,
    searchResults: [
      {
        id: "sr-y1",
        engine: "YANDEX",
        source: "real:YANDEX",
        url: "https://example.ru/news/ivan-petrov-profile",
        title: "Иван Петров — профиль в деловых СМИ",
        snippet: "Публикация описывает профессиональную деятельность субъекта.",
        rank: 1,
        classification: "neutral",
        reviewStatus: "PENDING",
        rawMetadata: { query: "Иван Петров биография", language: "ru", orionRegion: "RU" },
      },
      {
        id: "sr-y2",
        engine: "YANDEX",
        source: "real:YANDEX",
        url: "https://news.example.ru/article/sanctions-context",
        title: "Материал с упоминанием санкционного контекста",
        snippet: "Требует ручной проверки связи с субъектом.",
        rank: 2,
        classification: "adverse_media",
        reviewStatus: "PENDING",
        rawMetadata: { query: "Иван Петров биография", language: "ru", orionRegion: "RU", riskTheme: "adverse_media" },
      },
      {
        id: "sr-g1",
        engine: "GOOGLE",
        source: "real:GOOGLE",
        url: "https://www.example.com/ivan-petrov",
        title: "Ivan Petrov — corporate profile",
        snippet: "International mention of subject in corporate context.",
        rank: 1,
        classification: "neutral",
        reviewStatus: "PENDING",
        rawMetadata: { query: "Ivan Petrov biography", language: "en", orionRegion: "RU" },
      },
      {
        id: "sr-g2",
        engine: "GOOGLE",
        source: "real:GOOGLE",
        url: "https://registry.example.org/pep-list",
        title: "Public registry mention",
        snippet: "Possible PEP-related mention requires analyst review.",
        rank: 2,
        classification: "pep",
        reviewStatus: "PENDING",
        rawMetadata: { query: "Ivan Petrov biography", language: "en", orionRegion: "RU", riskTheme: "pep" },
      },
    ],
    searchSurfaces: [
      {
        id: "sf-img1",
        type: "IMAGE_RESULT",
        provider: "YANDEX",
        source: "real:YANDEX",
        region: "RU",
        language: "ru",
        query: "Иван Петров",
        title: "Фото из поиска",
        snippet: null,
        url: "https://images.example.ru/1.jpg",
        domain: "images.example.ru",
        imageUrl: "https://images.example.ru/1.jpg",
        thumbnailUrl: "https://images.example.ru/1-thumb.jpg",
        videoUrl: null,
        rank: 1,
        classification: "neutral",
        riskTheme: null,
        reviewStatus: "PENDING",
        rawMetadata: { orionRegion: "RU" },
      },
      {
        id: "sf-vid1",
        type: "VIDEO_RESULT",
        provider: "GOOGLE",
        source: "real:GOOGLE",
        region: "RU",
        language: "ru",
        query: "Иван Петров интервью",
        title: "Интервью на видеоплатформе",
        snippet: "Видеоматериал с упоминанием субъекта.",
        url: "https://video.example.com/watch/abc",
        domain: "video.example.com",
        imageUrl: null,
        thumbnailUrl: null,
        videoUrl: "https://video.example.com/watch/abc",
        rank: 1,
        classification: "neutral",
        riskTheme: null,
        reviewStatus: "PENDING",
        rawMetadata: { orionRegion: "RU" },
      },
      {
        id: "sf-kp1",
        type: "KNOWLEDGE_BLOCK",
        provider: "GOOGLE",
        source: "real:GOOGLE",
        region: "RU",
        language: "ru",
        query: "Иван Петров",
        title: "Иван Петров",
        snippet: "Краткая справка из блока знаний.",
        url: null,
        domain: null,
        imageUrl: null,
        thumbnailUrl: null,
        videoUrl: null,
        rank: 1,
        classification: "neutral",
        riskTheme: "identity_profile",
        reviewStatus: "PENDING",
        rawMetadata: { orionRegion: "RU" },
      },
      {
        id: "sf-sug1",
        type: "SUGGESTION",
        provider: "YANDEX",
        source: "real:YANDEX",
        region: "RU",
        language: "ru",
        query: "Иван Петров",
        title: "иван петров биография",
        snippet: null,
        url: null,
        domain: null,
        imageUrl: null,
        thumbnailUrl: null,
        videoUrl: null,
        rank: 1,
        classification: null,
        riskTheme: null,
        reviewStatus: "PENDING",
        rawMetadata: { orionRegion: "RU" },
      },
    ],
    databaseProfiles: [
      {
        id: "db-wc1",
        provider: "WORLD_CHECK",
        importMethod: "manual",
        hitSource: "screening",
        matchedName: "Ivan Petrov",
        matchType: "possible_match",
        matchScore: 0.72,
        reviewStatus: "PENDING",
        riskTypes: ["PEP"],
        summary: "Возможное совпадение в базе World-Check требует верификации.",
        rawMetadataSafe: {},
        importedAt: now,
      },
    ],
    riskFindings: [
      {
        id: "rf1",
        category: "adverse_media",
        severity: "MEDIUM",
        title: "Негативные публикации — требует проверки",
        summary: "Обнаружены материалы, которые могут содержать негативный контекст.",
        reviewStatus: "PENDING",
        evidenceRefs: [],
      },
    ],
    wikiChecks: [
      {
        exists: false,
        url: null,
        language: "ru",
        pageTitle: null,
      },
    ],
    providerAvailability: {
      used: ["yandex", "google"],
      unavailable: [],
    },
    lexis: {
      latestReady: null,
      latestAny: null,
      visualPageCount: 0,
      parsedSignals: 0,
      uploadExists: false,
    },
  };
}
