export const ORION_SLIDE_TEMPLATE_MAPPING: Record<string, string> = {
  cover_orion: "cover",
  toc_orion: "contents",
  section_toc_orion: "contents",
  executive_narrative_summary: "executive",
  compliance_risk_matrix: "risk_matrix",
  digital_profile_risk_overview: "overview",
  regional_audit_summary: "regional_summary",
  search_links_overview: "regional_results",
  top20_serp_matrix: "regional_results",
  adverse_themes_serp_examples: "regional_themes",
  search_suggestions: "regional_suggestions",
  wikipedia_profile: "regional_wikipedia",
  image_results_analysis: "regional_images",
  knowledge_panel_analysis: "regional_knowledge",
  related_queries_analysis: "regional_related_queries",
  dow_jones_profile_overview: "compliance_overview",
  world_check_profile_overview: "compliance_overview",
  lexisnexis_profile_overview: "lexis_intro",
  lexisnexis_visual_page: "lexis_visual_page",
  lexisnexis_unavailable_fallback: "lexis_analytics",
  offer_client_pain: "offer_cover",
  offer_context: "offer_product_overview",
  offer_service_map: "offer_process",
  offer_solution_divider: "offer_cover",
  offer_before_after: "offer_solution_objective",
  offer_implementation_plan: "offer_solution_workplan",
  offer_budget_table: "offer_solution_pricing",
  offer_case_study: "offer_product_overview",
  how_to_start: "offer_about",
  about_company: "offer_about",
  competition: "offer_product_overview",
  ai_search_impact: "offer_product_overview",
};

